### ISSUE TITLE
Already run migrations are run again if there was error in migration

### ISSUE THREAD

**Issue by tuukkamustonen** [klen/peewee_migrate#10]
Lets say there are migrations 001 and 002. 001 succeeds but 002 does not. When you re-run migrations, library tries to re-run 001 even though it's already applied in the database.

In `BaseRouter.migrator` there is:

        for name in self.done:
            self.run_one(name, migrator)

I'm not sure why that is there, what is the logic, but removing the block fixes the issue.

**Comment by klen** [comment]
You shouldn't do it. Yes, the lib runs old migration again but in "fake" mode. The lib needs do this for creation of "virtual" time models, the virtual models are using for "--auto" migrations and inside migration' scripts for data migrations. If you have a data migration, you should use something like this:

WRONG! DONT DO THIS!

    from mymodels import MyModel

    def migrate(migrator, database, fake=false, **kwargs):
         """Update something in db."""
        for obj in MyModel.select():
             obj.field = 'a new value'

RIGHT WAY:

    def migrate(migrator, database, fake=false, **kwargs):
         """Update something in db."""
        MyModel = migrator.orm['mymodel']  # Return virtual model in current migration state
        for obj in MyModel.select():
             obj.field = 'a new value'

**Comment by tuukkamustonen** [comment]
Oh. That hits me as a big inconvenience, and having to dig the models from `Migrator` sounds quite weird - I'm sure you got the technical reasoning for it, but is there room for improvement?

At least it should be documented.
