### ISSUE TITLE
Peewee Migrate 2: support is here

### ISSUE THREAD

**Issue by spumer** [klen/peewee_migrate#172]
Guys. Till ``klen`` in "vacation" i started a fork with critical fixups.

PR and suggestions are welcome, Make This Package Great Again 👍 

https://github.com/spumer/peewee_migrate2

**Comment by klen** [comment]
@spumer Thank you for your work. I've come back and plan to continue the work. but I appreciate to your fork exists.

**Comment by spumer** [comment]
@klen I started discussion with you via email :)
Email taken from github page, i hope it's right
