### ISSUE TITLE
Bug report: [PLEASE DESCRIBE]

### ISSUE THREAD

**Issue by konradkur** [klen/peewee_migrate#205]
Hi,

i use peewee on many microservices, the time has come for the migration system, i decided on the automatic solution.

I chose your solution, but I have an error at the start
adds one new field to a database table

**is_root2 = peewee.BooleanField(default=False)**

and the command migrate returns

**ValueError: is_root2 is not null but has no default**

`"""Peewee migrations -- 002_next.py.

Some examples (model - class or model name)::

    > Model = migrator.orm['model_name']            # Return model in current state by name

    > migrator.sql(sql)                             # Run custom SQL
    > migrator.python(func, *args, **kwargs)        # Run python code
    > migrator.create_model(Model)                  # Create a model (could be used as decorator)
    > migrator.remove_model(model, cascade=True)    # Remove a model
    > migrator.add_fields(model, **fields)          # Add fields to a model
    > migrator.change_fields(model, **fields)       # Change fields
    > migrator.remove_fields(model, *field_names, cascade=True)
    > migrator.rename_field(model, old_field_name, new_field_name)
    > migrator.rename_table(model, new_table_name)
    > migrator.add_index(model, *col_names, unique=False)
    > migrator.drop_index(model, *col_names)
    > migrator.add_not_null(model, *field_names)
    > migrator.drop_not_null(model, *field_names)
    > migrator.add_default(model, field_name, default)

"""

import datetime as dt
import peewee as pw
from decimal import ROUND_HALF_EVEN

try:
    import playhouse.postgres_ext as pw_pext
except ImportError:
    pass

SQL = pw.SQL

def migrate(migrator, database, fake=False, **kwargs):
    """Write your migrations here."""

    migrator.add_fields(
        'catalog',

        is_root2=pw.BooleanField(constraints=[SQL("DEFAULT False")]))

    migrator.change_fields('catalog', is_root=pw.BooleanField(constraints=[SQL("DEFAULT False")]))

    migrator.change_fields('file', is_display=pw.BooleanField(constraints=[SQL("DEFAULT True")]))

    migrator.change_fields('fileddeletionpermissions', deletion=pw.IntegerField(constraints=[SQL("DEFAULT 770")]))

    migrator.change_fields('filedvisibilitypermissions', visibility=pw.IntegerField(constraints=[SQL("DEFAULT 770")]))

    migrator.change_fields('invoice', is_has_product=pw.BooleanField(constraints=[SQL("DEFAULT False")]),
        is_has_service=pw.BooleanField(constraints=[SQL("DEFAULT False")]))

def rollback(migrator, database, fake=False, **kwargs):
    """Write your rollback migrations here."""

    migrator.remove_fields('catalog', 'is_root2')
`

I changed one field in the database table, and the migration shows how I would change more fields, why?

is this solution stable at all? Better to write migrations by hand?

I am using the latest version of peewee and the migrator
`peewee==3.14.4
peewee-migrate==1.4.3`

**Comment by klen** [comment]
@konradkur Thank you for the feedback 🙏 Auto migrations have been fixed in the latest version. Please check.
