### ISSUE TITLE
Bug report: Failed when reference a custom fields

### ISSUE THREAD

**Issue by lovexuan** [klen/peewee_migrate#209]
The model definition seems like:

```python
class MySQLTimestampField(TimestampField):
    field_type = 'timestamp'

class Table1(Model):
    timestamp_field = MySQLTimestampField()
```

and the generated code seems like:

```python
import peewee as pw

...
@migrator.create_model
class Table1(pw.Model):
    timestamp_field = pw.MySQLTimestampField()
```

When I execute `router.run()`, it raise `AttributeError: module 'peewee' has no attribute 'MySQLTimestampField'`.

The suggestion is, scan all the referenced fields first, and get module by `class.__module__`, then generate codes by this relation.

**Comment by klen** [comment]
should be fixed in the latest versions
