### ISSUE TITLE
Bug report: Git tag for 1.7.0 is missing

### ISSUE THREAD

**Issue by mweinelt** [klen/peewee_migrate#224]
**Describe the bug**
The Git tag for version 1.7.0 is missing.

**Expected behavior**
Releases that are uploaded to pypi should also be tagged on Git.

**Additional context**
We are pulling the sources for pewee-migrate on nixpkgs from git, so we can run the tests downstream.

**Comment by klen** [comment]
@mweinelt thank you, fixed
