### ISSUE TITLE
Peewee version dependency

### ISSUE THREAD

**Issue by MiguelSR** [klen/peewee_migrate#42]
Hello!

In the docs you state as only dependency: "python 2.7,3.3,3.4", which I accomplish.

But there's also a dependency of peewee >= 2.8.5, as specified in requirements.txt. I'm using peewee 2.6 so I can't use this library.
Do you think you could lower your peewee requirement to 2.6.0 or it is a must to have it set on 2.8.5?

In that case, perhaps it would be a good idea to write it down on the requirements section of the docs page :).

Thank you very much,
Miguel.

**Comment by klen** [comment]
Updated readme.
