### ISSUE TITLE
Import settings.py in conf.py

### ISSUE THREAD

**Issue by 0x836** [klen/peewee_migrate#47]
I noticed, we can write conf file in migration directory and setup settings about DB for example - https://github.com/klen/peewee_migrate/blob/develop/peewee_migrate/cli.py#L26

If I create migrations/conf.py with
`
DATABASE = 'postgresql://user:pass@host/db'
`
it works fine.
But if I want to confugure DATABASE variable from settings.py (for example) like this

```
import settings
DATABASE = 'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}'.format(
    DB_HOST=settings.DB_HOST,
    DB_NAME=settings.DB_NAME,
    DB_USER=settings.DB_USER,
    DB_PASSWORD=settings.DB_PASSWORD,
)
```
I got 
> ModuleNotFoundError: No module named 'settings'

Are there any solutions of this problem?

**Comment by klen** [comment]
Ensure that sys.path contains a directory with the settings.py module. You can configure sys.path right into the script.

**Comment by NilsJPWerner** [comment]
Adding the root directory to sys.path doesn't seem to actually work:

`import sys
import os
sys.path.append(os.path.dirname(sys.path[0]))

from config.settings import DB_SETTINGS

DATABASE = 'postgresql://{user}:{password}@{host}/{database}'.format(
    host=DB_SETTINGS["host"],
    database=DB_SETTINGS["database"],
    user=DB_SETTINGS["user"],
    password=DB_SETTINGS["password"],
)`

I still get:

`ModuleNotFoundError: No module named 'config'`

**Comment by NilsJPWerner** [comment]
I got it to work, it needs to use "__file__" . Here is the full snippet in my migrations/conf.py

```
import os
sys.path.append(os.path.dirname(sys.path[0]))

from config.settings import DB_SETTINGS

DATABASE = 'postgresql://{user}:{password}@{host}/{database}'.format(
    host=DB_SETTINGS["host"],
    database=DB_SETTINGS["database"],
    user=DB_SETTINGS["user"],
    password=DB_SETTINGS["password"],
)
```
