### ISSUE TITLE
BaseRouter.todo raises not implemented

### ISSUE THREAD

**Issue by dingus9** [klen/peewee_migrate#6]
So this appears to make things completely unusable as the NotImplementedError of BaseRouter.todo always raises NotImlementedError
[router.py#L41-L43](https://github.com/klen/peewee_migrate/blob/develop/peewee_migrate/router.py#L41-L43)

Where are you going with all that? Do you need me to implement something there?
Nick

**Comment by klen** [comment]
How do you use it? BaseRouter is kind of abstract. Currently, Router (file router exactly) is mostly supported.

**Comment by dingus9** [comment]
My main goal was is to store migrations within the application. This is most easily done by providing them in as proper python modules. It simplifies the setup.py and makes it easy to access the migrations after the module has been installed from any python module.

Also because they are modules they do not need to be parsed and run... This makes debugging a migration just like any other python module as well as quickly highlights import errors and other runtime things.

Also not that it matters too much but you can import logging or other modules and they should behave as expected since you are operating within the standard python execution flow.

### Simplified example:
**Assume**:
myapp/migrations/__init__.py
myapp/migrations/0_1_0.py
myapp/migrations/0_2_0.py
myapp/migrations/0_6_1.py

myapp/migrate.py
```python
from peewee import *
from peewee_migrate.router import ModuleRouter
DB = Proxy()

DB.initialize(connect('sqlite:///mydb.db'))
router = Router(DB, migrate_module='myapp.migrations')

for migration in ('0_1_0', '0_2_0', '0_6_1'):
    router.run(migration)
```
### More verbose example:
[Gist](https://gist.github.com/dingus9/61877ee4fda75def6bf37d41fd0d8642)

**Comment by dingus9** [comment]
Honestly I would recommend moving to this for the cli as well since you can just specify which python module to import like:
`peewee_migrate --module 'myapp.migrations.semantic' --min '0.1.2' --max '3.0.0'`

pretty much any migrations directory can be a module by adding the __init__.py

**Comment by dingus9** [comment]
Back to the BaseRouter... when I added my logic it didn't have those NotImplementedError calls... I am thinking you want intend to define the methods that raise NotImplementedError in each subclass is that correct?

**Comment by klen** [comment]
Actually, I did a lot of updates since your last PR. I think you need to reinvestigate how it works and update ModuleRouter as well.
