### ISSUE TITLE
Loosen dependency versions

### ISSUE THREAD

**Issue by tuukkamustonen** [klen/peewee_migrate#7]
In `requirements.txt`:

    cached_property     == 1.3.0
    click               == 6.4
    mock                == 1.3.0
    peewee              >= 2.8.0

Would it be possible to depend from a minimum only version (as with peewee)? Requiring exact versions is pretty annoying in projects, that happen to want to use a newer version.

**Comment by klen** [comment]
That the point, will do this. Thank you!
