### ISSUE TITLE
Support raw SQL files

### ISSUE THREAD

**Issue by tuukkamustonen** [klen/peewee_migrate#8]
In my standard use case, I have no need for rollback and no need for peewee's abstractions, really, but I would like to keep that as an option. To reduce boilerplate ever so slightly, I would like to load raw `.sql` files from directory, as an alternative to python scripts.

Would you be willing to merge something like this if I created a PR:

```python
class SqlRouter(Router):

    filemask = re.compile(r"[\d]{3}_[^\.]+\.(py|sql)$")

    @property
    def todo(self):
        """Scan migrations in file system."""
        if not os.path.exists(self.migrate_dir):
            self.logger.warn('Migration directory: %s does not exists.', self.migrate_dir)
            os.makedirs(self.migrate_dir)
        return sorted(
            f.rpartition('.')[0] for f in os.listdir(self.migrate_dir) if self.filemask.match(f))

    def read(self, name):
        """Read migration from SQL or python file."""
        sql_file = os.path.join(self.migrate_dir, name + '.sql')
        if os.path.isfile(sql_file):
            data = ''
            with open(sql_file) as f:
                for line in f.readlines():
                    if line and not line.startswith('--'):
                        data += line
            return lambda mg, db, *args, **kwargs: db.execute_sql(data), VOID
        return super().read(name)
```

Note that the only thing needing change in `todo()` is from `''.join(f[:-3])` to `f.rpartition('.')[0]` to support different length of file suffix. That could be improved in `Router` already.

**Comment by klen** [comment]
Let see the PR.

**Comment by tuukkamustonen** [comment]
After think about it a bit more, I am afraid this would not be such a good idea or in the scope of the project. The library seems to imbue some magic for the peewee models, and mixing and matching SQL migrations together with python migrations would probably introduce issues as not every change is available to the next migration.
